### ISSUE TITLE
Failure on VM deletion

### ISSUE THREAD

**Issue by ulide4** [OpenNebula/addon-linstor#1]
Hi there,
I am testing the linstor addon according the installation instructions and I could successfully create a VM. Live migration etc. is also working fine. When I try to delete the VM the VM goes in to failure state with following log output:

Sun Nov 25 15:11:05 2018 [Z0][VM][I]: New LCM state is SHUTDOWN
Sun Nov 25 15:11:07 2018 [Z0][VMM][I]: ExitCode: 0
Sun Nov 25 15:11:07 2018 [Z0][VMM][I]: Successfully execute virtualization driver operation: cancel.
Sun Nov 25 15:11:07 2018 [Z0][VMM][I]: Successfully execute network driver operation: clean.
Sun Nov 25 15:11:07 2018 [Z0][VM][I]: New LCM state is EPILOG
Sun Nov 25 15:11:11 2018 [Z0][TM][I]: Command execution failed (exit code: 1): /var/lib/one/remotes/tm/linstor/delete srv432:/var/lib/one//datastores/0/1/disk.0 1 100
Sun Nov 25 15:11:11 2018 [Z0][TM][I]: Traceback (most recent call last):
Sun Nov 25 15:11:11 2018 [Z0][TM][I]: File "/var/lib/one/remotes/tm/linstor/delete", line 87, in <module>
Sun Nov 25 15:11:11 2018 [Z0][TM][I]: main()
Sun Nov 25 15:11:11 2018 [Z0][TM][I]: File "/var/lib/one/remotes/tm/linstor/delete", line 81, in main
Sun Nov 25 15:11:11 2018 [Z0][TM][I]: res.delete()
Sun Nov 25 15:11:11 2018 [Z0][TM][I]: File "/usr/lib/python2.7/site-packages/linstor_helper/resource.py", line 155, in delete
Sun Nov 25 15:11:11 2018 [Z0][TM][I]: for snap in self.snapshots():
Sun Nov 25 15:11:11 2018 [Z0][TM][I]: File "/usr/lib/python2.7/site-packages/linstor_helper/resource.py", line 215, in snapshots
Sun Nov 25 15:11:11 2018 [Z0][TM][I]: "snapshot_dfns"
Sun Nov 25 15:11:11 2018 [Z0][TM][I]: KeyError: 'snapshot_dfns'
Sun Nov 25 15:11:11 2018 [Z0][TM][E]: Error executing image transfer script
Sun Nov 25 15:11:11 2018 [Z0][VM][I]: New LCM state is EPILOG_FAILURE

Environment is Open Nebula 5.6.1 on CentOS 7.5. Two KVM Nodes and the linstor controller runs on the OpenNebula Frontend Server. linstor satellite, controller, drbd etc. on the current release as of this writing.

Please help....

Thanks & Best Regards
Uli

**Comment by deleteriousEffect** [comment]
Could you please provide the output of `linstor -m r l` with your VMs as they are right before deletion?

**Comment by ulide4** [comment]
there you go... (hmm...indentation gets lost while pasting :-/ )
[oneadmin@srv451 ~]$ linstor -m r l
[
  {
    "resource_states": [
      {
        "vlm_states": [
          {
            "disk_state": "UpToDate", 
            "vlm_nr": 0
          }
        ], 
        "in_use": false, 
        "rsc_name": "OpenNebula-Image-0", 
        "node_name": "srv450"
      }, 
      {
        "vlm_states": [
          {
            "disk_state": "UpToDate", 
            "vlm_nr": 0
          }
        ], 
        "in_use": true, 
        "rsc_name": "OpenNebula-Image-0-vm0-disk0", 
        "node_name": "srv450"
      }, 
      {
        "vlm_states": [
          {
            "disk_state": "UpToDate", 
            "vlm_nr": 0
          }
        ], 
        "in_use": false, 
        "rsc_name": "OpenNebula-Image-0", 
        "node_name": "srv449"
      }, 
      {
        "vlm_states": [
          {
            "disk_state": "UpToDate", 
            "vlm_nr": 0
          }
        ], 
        "in_use": false, 
        "rsc_name": "OpenNebula-Image-0-vm0-disk0", 
        "node_name": "srv449"
      }
    ], 
    "resources": [
      {
        "vlms": [
          {
            "meta_disk": "internal", 
            "device_path": "/dev/drbd1000", 
            "vlm_nr": 0, 
            "stor_pool_name": "drbdpool", 
            "stor_pool_uuid": "ef75b1e1-5837-44cf-9ccd-dd225d72113a", 
            "vlm_minor_nr": 1000, 
            "backing_disk": "/dev/vg-drbdpool/OpenNebula-Image-0_00000", 
            "vlm_uuid": "8c173141-a0b5-43bf-9571-2fe53c4abb54", 
            "vlm_dfn_uuid": "8f90d41c-9e82-4c71-a71e-f2c2254b1a85"
          }
        ], 
        "node_uuid": "6efd59d0-9ead-4380-9c2d-c8573533bb7d", 
        "uuid": "f6b4c187-c94d-4b0e-9962-eab28679e6e0", 
        "node_name": "srv449", 
        "node_id": 0, 
        "props": [
          {
            "value": "drbdpool", 
            "key": "AutoSelectedStorPoolName"
          }, 
          {
            "value": "7", 
            "key": "PeerSlots"
          }, 
          {
            "value": "drbdpool", 
            "key": "StorPoolName"
          }
        ], 
        "rsc_dfn_uuid": "b16faf4e-7937-47ae-9626-ca0bdde53124", 
        "name": "OpenNebula-Image-0"
      }, 
      {
        "vlms": [
          {
            "meta_disk": "internal", 
            "device_path": "/dev/drbd1000", 
            "vlm_nr": 0, 
            "stor_pool_name": "drbdpool", 
            "stor_pool_uuid": "e3c768f5-ea8c-4b37-9849-3a4eccb73e75", 
            "vlm_minor_nr": 1000, 
            "backing_disk": "/dev/vg-drbdpool/OpenNebula-Image-0_00000", 
            "vlm_uuid": "936d8eea-563e-4c85-8a78-a2b72be3b6f7", 
            "vlm_dfn_uuid": "8f90d41c-9e82-4c71-a71e-f2c2254b1a85"
          }
        ], 
        "node_uuid": "57f3e92a-fab4-4874-84e0-7ce9af2454fb", 
        "uuid": "daf950ef-faca-44ba-8d8f-09f35cbb2265", 
        "node_name": "srv450", 
        "node_id": 1, 
        "props": [
          {
            "value": "drbdpool", 
            "key": "AutoSelectedStorPoolName"
          }, 
          {
            "value": "7", 
            "key": "PeerSlots"
          }, 
          {
            "value": "drbdpool", 
            "key": "StorPoolName"
          }
        ], 
        "rsc_dfn_uuid": "b16faf4e-7937-47ae-9626-ca0bdde53124", 
        "name": "OpenNebula-Image-0"
      }, 
      {
        "vlms": [
          {
            "meta_disk": "internal", 
            "device_path": "/dev/drbd1001", 
            "vlm_nr": 0, 
            "stor_pool_name": "drbdpool", 
            "stor_pool_uuid": "ef75b1e1-5837-44cf-9ccd-dd225d72113a", 
            "vlm_minor_nr": 1001, 
            "backing_disk": "/dev/vg-drbdpool/OpenNebula-Image-0-vm0-disk0_00000", 
            "vlm_uuid": "560d6ee8-6584-41af-93ed-1a82a1ca4209", 
            "vlm_props": [
              {
                "value": "OpenNebula-Image-0", 
                "key": "RestoreFromResource"
              }, 
              {
                "value": "for-OpenNebula-Image-0-vm0-disk0", 
                "key": "RestoreFromSnapshot"
              }
            ], 
            "vlm_dfn_uuid": "b493a8d5-e5f2-4b3a-be34-cee99490c659"
          }
        ], 
        "node_uuid": "6efd59d0-9ead-4380-9c2d-c8573533bb7d", 
        "uuid": "9eda4f76-3cb3-4a78-afef-2d5aea27326c", 
        "node_name": "srv449", 
        "node_id": 0, 
        "props": [
          {
            "value": "7", 
            "key": "PeerSlots"
          }
        ], 
        "rsc_dfn_uuid": "8d18be24-a546-4f25-a81d-9f83e57c14be", 
        "name": "OpenNebula-Image-0-vm0-disk0"
      }, 
      {
        "vlms": [
          {
            "meta_disk": "internal", 
            "device_path": "/dev/drbd1001", 
            "vlm_nr": 0, 
            "stor_pool_name": "drbdpool", 
            "stor_pool_uuid": "e3c768f5-ea8c-4b37-9849-3a4eccb73e75", 
            "vlm_minor_nr": 1001, 
            "backing_disk": "/dev/vg-drbdpool/OpenNebula-Image-0-vm0-disk0_00000", 
            "vlm_uuid": "4f0e4599-27c8-420b-9836-139cdc4c5b97", 
            "vlm_props": [
              {
                "value": "OpenNebula-Image-0", 
                "key": "RestoreFromResource"
              }, 
              {
                "value": "for-OpenNebula-Image-0-vm0-disk0", 
                "key": "RestoreFromSnapshot"
              }
            ], 
            "vlm_dfn_uuid": "b493a8d5-e5f2-4b3a-be34-cee99490c659"
          }
        ], 
        "node_uuid": "57f3e92a-fab4-4874-84e0-7ce9af2454fb", 
        "uuid": "7ccbcfd8-009b-480c-8c6b-1b22a3fad86f", 
        "node_name": "srv450", 
        "node_id": 1, 
        "props": [
          {
            "value": "7", 
            "key": "PeerSlots"
          }
        ], 
        "rsc_dfn_uuid": "8d18be24-a546-4f25-a81d-9f83e57c14be", 
        "name": "OpenNebula-Image-0-vm0-disk0"
      }
    ]
  }
]

**Comment by deleteriousEffect** [comment]
closed by 2bccbdc

**Comment by ulide4** [comment]
I can confim that deletion is working now. Thanks
