### ISSUE TITLE
Choosing image datastore while creating new VM

### ISSUE THREAD

**Issue by zheliazkov** [OpenNebula/addon-linstor#12]
Hello @rp-,

I'm trying to make the following:

- Create two Image datastores - one with bigger place-count and another with lower
- Create one system datastore
- Be able to choose where to deploy the freshly created VMs

I've made the first two things but when creating new VM, I'm able to choose only system datastore.

Read about the differences and the [blog](https://linbit.com/blog/how-setup-linstor-opennebula/) says that system datastore is used only for small contextual images and the [OpenNebula docs](https://docs.opennebula.io/5.12/operation/host_cluster_management/datastore_guide.html) says that The Image Datastore, stores the Image repository and The System Datastore holds disk for running virtual machines, usually cloned from the Image Datastore, which is different.

If the blog is right - why cannot choose a prefer datastore of type image? And if the doc's are right - why all of my VM disks are placed on the Image datastore (seen in the linstor rd l).

Thanks in advance :)

BR,
Plamen

**Comment by rp-** [comment]
From my knowledge the image datastore depends, in which image datastore the base image of the VM template is.
On instantiation you can only choose on/in which system datastore the the VM should run.
