### ISSUE TITLE
Support for live snapshots

### ISSUE THREAD

**Issue by chiraganand-e2e** [OpenNebula/addon-linstor#13]
Hi, is there a timeline for when this driver would support live snapshots? Right now, we just get an operation not supported message. This is critical for our business that we use the live snapshotting feature.

**Comment by rp-** [comment]
As I just rediscovered(was hinted) on this, live snapshots will work if all VM disks use qcow2 as format.
It is just not possible to have RAW disks, as there is no way the plugin could opennebula/libvirt tell where to put the RAM image.
