### ISSUE TITLE
Update Drivers for 6.8 release

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/addon-linstor#14]
In relation with OpenNebula/one#6162 issue, we have updated the datastore drivers to take the driver message action through stdin. The change is rather simple, [just read DRV_ACTION from stdin, see for example this change](https://github.com/OpenNebula/one/commit/5a83b45ce174da10db3eaa180bdd07ad7ed2d98d#diff-a58dd905a6e6a8d33c0bf41499ebf1fea0a5976ad3ac3f782e841c7ecd5397ceR40), something like:

```
DRV_ACTION=`cat -`
ID=$1

```
This needs to happen for every `datastore/*` action file and `tm/monitor ` script ([for example see here](https://github.com/OpenNebula/one/commit/5a83b45ce174da10db3eaa180bdd07ad7ed2d98d#diff-3ff908a298d9757a64fa7e1482ee37150a1c3e6e5438bbae9dd266643c6bd759))

**Note**: Releases 6.4.x and 6.6.x will support both behaviors (configurable through oned.conf) to preserve compatibility

**Comment by rp-** [comment]
As far as I see your change only supports the new behavior.
Is there a way to check which one is configured?
Otherwise we would need to provide 2 versions of the drivers?
@rsmontero

**Comment by rp-** [comment]
@rsmontero 
accidentally deleted my comment.
Question still stands: How can we plugin provider distinguish between < 6.8 versions?
You just ship the updated drivers with 6.8, but we deliver same plugin for all versions.

**Comment by rsmontero** [comment]
This is an interesting question. There is in fact a way to find out the version, [there is a file](https://github.com/OpenNebula/one/blob/master/src/im_mad/remotes/VERSION) installed as `/var/lib/one/remotes/VERSION` with the information. 

So probably you can check with the contents of that file, or simply the number of arguments of the program: pre 6.8 you should have 2, post 6.8 will be just 1.

**Comment by rp-** [comment]
done 9e829f205e627d46259eba56668817abb40966b8
