### ISSUE TITLE
Support native OpenNebula backup

### ISSUE THREAD

**Issue by antnjakushin** [OpenNebula/addon-linstor#15]
Is it planned to support native OpenNebula backup functionality? 
Now I can create a backup (after adding files (postbackup, prebackup, postbackup_live, prebackup_live) in  /var/lib/one/remotes/tm/linstor/) and the backups are stored in backup storage (rsync).
But I can't restore with the following error:
```
Tue Sep 26 16:04:13 2023 : Error copying image in the datastore: Traceback (most recent call last): File "/usr/lib/python3.6/site-packages/one/util.py", line 392, in run_main main_func() File "/var/lib/one/remotes/datastore/linstor/cp", line 60, in main "-", File "/usr/lib/python3.6/site-packages/one/util.py", line 284, in set_downloader_args return _get_subp_out(_source(LIBFS, "set_downloader_args", string_args)) File "/usr/lib/python3.6/site-packages/one/util.py", line 103, in _get_subp_out raise subprocess.CalledProcessError(returncode=rc, cmd=cmd, output=out, stderr=err) subprocess.CalledProcessError: Command '['bash', '-c', 'source /var/lib/one/remotes//datastore/libfs.sh && set_downloader_args "" "" "" "" rsync://102/0:8fa45e//var/lib/one//datastores/102/0/8fa45e/disk.0.0\n -']' returned non-zero exit status 127. ERROR: Command ['bash', '-c', 'source /var/lib/one/remotes//datastore/libfs.sh && set_downloader_args "" "" "" "" rsync://102/0:8fa45e//var/lib/one//datastores/102/0/8fa45e/disk.0.0\n -'] returned error: 'rsync://102/0:8fa45e//var/lib/one//datastores/102/0/8fa45e/disk.0.0' bash: line 1: -: command not found
```

**Comment by antnjakushin** [comment]
May be this is related: https://github.com/OpenNebula/one/commit/5e37e52e397673ffdbe23bc7fbcf5ac410264758

**Comment by rp-** [comment]
Currently no real plans, but if I got time I can have a look, whats missing to support them.

**Comment by ryan-ronnander** [comment]
@antnjakushin - Which location did you copy the postbackup, prebackup, postbackup_live, prebackup_live files from?

I seem to have this working on the latest OpenNebula 6.8 + version 2.2.2 of this plugin. 

On the controller try running (as root):
```shell
cp /var/lib/one/remotes/tm/shared/*backup* /var/lib/one/remotes/tm/linstor/
chown oneadmin:oneadmin /var/lib/one/remotes/tm/linstor/*
chmod 750 /var/lib/one/remotes/tm/linstor/*
```
After the above commands, I was able to use the OpenNebula backups feature (rsync) successfully for backing up as well as restoring VMs (running and non-running).

**Comment by antnjakushin** [comment]
Yes, I copied files in the same way. This did not work on Opennebula 6.6, but now on version 6.6.3 it works.
I think we need to include these files in the plugin package installer.

**Comment by rp-** [comment]
9f40af4756b8a4e638c92dacd455a743d217d229
