### ISSUE TITLE
After (hard) reboot of storage node state of (disk-)resource (attached to a VM) is unknown on rebooted node

### ISSUE THREAD

**Issue by ulide4** [OpenNebula/addon-linstor#2]
Hi again,
I am currently in the status of testing what can go wrong and have switched off the passive storage node (resource state=unused) and switched it on again to see if replication starts again.
See detailed history below (FYI, that the text is partly crossed  is unintended)

SETUP: 
srv485 -> linstor controller & OpenNebula Frontend
srv484 & srv483 -> linstor satellite & storage node & OpenNebula KVM host, 
datatore policy -> LINSTOR_AUTO_PLACE = 2
OS: Centos 7.5 (same error behaviour on Ubuntu 18.04 btw)

VM creation, live migration, VM deletion is working fine. 
Is there conceptually something I am missing or is this unexpected behavior? 

oneadmin@srv485:~$ linstor resource list
╭────────────────────────────────────────────────────────╮
┊ ResourceName       ┊ Node   ┊ Port ┊ Usage  ┊    State ┊
╞┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╡
┊ OpenNebula-Image-0 ┊ srv483 ┊ 7000 ┊ Unused ┊ UpToDate ┊
┊ OpenNebula-Image-0 ┊ srv484 ┊ 7000 ┊ Unused ┊ UpToDate ┊
╰────────────────────────────────────────────────────────╯

oneadmin@srv485:~$ onetemplate instantiate 0
VM ID: 0

oneadmin@srv485:~$ linstor resource list
╭──────────────────────────────────────────────────────────────────╮
┊ ResourceName                 ┊ Node   ┊ Port ┊ Usage  ┊    State ┊
╞┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╡
┊ OpenNebula-Image-0           ┊ srv483 ┊ 7000 ┊ Unused ┊ UpToDate ┊
┊ OpenNebula-Image-0           ┊ srv484 ┊ 7000 ┊ Unused ┊ UpToDate ┊
┊ OpenNebula-Image-0-vm0-disk0 ┊ srv483 ┊ 7001 ┊ Unused ┊ UpToDate ┊
┊ OpenNebula-Image-0-vm0-disk0 ┊ srv484 ┊ 7001 ┊ InUse  ┊ UpToDate ┊
╰──────────────────────────────────────────────────────────────────╯

SWITCHING OFF NODE srv483 

oneadmin@srv485:~$ linstor resource list
╭──────────────────────────────────────────────────────────────────╮
┊ ResourceName                 ┊ Node   ┊ Port ┊ Usage  ┊    State ┊
╞┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╡
┊ OpenNebula-Image-0           ┊ srv483 ┊ 7000 ┊        ┊  Unknown ┊
┊ OpenNebula-Image-0           ┊ srv484 ┊ 7000 ┊ Unused ┊ UpToDate ┊
┊ OpenNebula-Image-0-vm0-disk0 ┊ srv483 ┊ 7001 ┊        ┊  Unknown ┊
┊ OpenNebula-Image-0-vm0-disk0 ┊ srv484 ┊ 7001 ┊ InUse  ┊ UpToDate ┊
╰──────────────────────────────────────────────────────────────────╯

oneadmin@srv485:~$ linstor node list
╭─────────────────────────────────────────────────────────────────────╮
┊ Node   ┊ NodeType  ┊ Addresses                            ┊ State   ┊
╞┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╡
┊ srv483 ┊ SATELLITE ┊ 100.80.0.15,100.80.0.15:3366 (PLAIN) ┊ OFFLINE ┊
┊ srv484 ┊ SATELLITE ┊ 100.80.0.16,100.80.0.16:3366 (PLAIN) ┊ Online  ┊
╰─────────────────────────────────────────────────────────────────────╯

SWITCHING ON node srv483

oneadmin@srv485:~$  linstor node list
╭────────────────────────────────────────────────────────────────────╮
┊ Node   ┊ NodeType  ┊ Addresses                            ┊ State  ┊
╞┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╡
┊ srv483 ┊ SATELLITE ┊ 100.80.0.15,100.80.0.15:3366 (PLAIN) ┊ Online ┊
┊ srv484 ┊ SATELLITE ┊ 100.80.0.16,100.80.0.16:3366 (PLAIN) ┊ Online ┊
╰────────────────────────────────────────────────────────────────────╯
oneadmin@srv485:~$ linstor resource list
╭──────────────────────────────────────────────────────────────────╮
┊ ResourceName                 ┊ Node   ┊ Port ┊ Usage  ┊    State ┊
╞┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╡
┊ OpenNebula-Image-0           ┊ srv483 ┊ 7000 ┊ Unused ┊ UpToDate ┊
┊ OpenNebula-Image-0           ┊ srv484 ┊ 7000 ┊ Unused ┊ UpToDate ┊
┊ OpenNebula-Image-0-vm0-disk0 ┊ srv483 ┊ 7001 ┊        ┊  Unknown ┊
┊ OpenNebula-Image-0-vm0-disk0 ┊ srv484 ┊ 7001 ┊ InUse  ┊ UpToDate ┊
╰──────────────────────────────────────────────────────────────────╯

oneadmin@srv485:~$ linstor error-reports list
╭────────────────────────────────────────────────────────────╮
┊ Nr. ┊ Id                    ┊ Datetime            ┊ Node   ┊
╞┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╡
┊   1 ┊ 5BFE9E8A-90340-000000 ┊ 2018-11-28 14:56:47 ┊ srv483 ┊
╰────────────────────────────────────────────────────────────╯
oneadmin@srv485:~$ linstor error-reports show  5BFE9E8A-90340-000000
ERROR REPORT 5BFE9E8A-90340-000000

============================================================

Application:                        LINBIT® LINSTOR
Module:                             Satellite
Version:                            0.7.3
Build ID:                           6e47dd2cb440e65727889f4c2f7423996153bdb3
Build time:                         2018-11-22T10:55:51+00:00
Error time:                         2018-11-28 14:56:47
Node:                               srv483

============================================================

Reported error:
===============

Description:
    Operations on resource 'OpenNebula-Image-0-vm0-disk0' were aborted
Cause:
    Meta data creation for volume 0 failed because the execution of an external command failed
Correction:
    - Check whether the required software is installed
    - Check whether the application's search path includes the location
      of the external software
    - Check whether the application has execute permission for the external command

Category:                           LinStorException
Class name:                         ResourceException
Class canonical name:               com.linbit.linstor.core.DrbdDeviceHandler.ResourceException
Generated at:                       Method 'createResourceMetaData', Source file 'DrbdDeviceHandler.java', Line #1524

Error message:                      Meta data creation for resource 'OpenNebula-Image-0-vm0-disk0' volume 0 failed

Error context:
    Meta data creation for resource 'OpenNebula-Image-0-vm0-disk0' volume 0 failed

Call backtrace:

    Method                                   Native Class:Line number
    createResourceMetaData                   N      com.linbit.linstor.core.DrbdDeviceHandler:1524
    createResource                           N      com.linbit.linstor.core.DrbdDeviceHandler:1138
    dispatchResource                         N      com.linbit.linstor.core.DrbdDeviceHandler:364
    run                                      N      com.linbit.linstor.core.DeviceManagerImpl$DeviceHandlerInvocation:1225
    run                                      N      com.linbit.WorkerPool$WorkerThread:179

Caused by:
==========

Description:
    Execution of the external command 'drbdadm' failed.
Cause:
    The external command exited with error code 20.
Correction:
    - Check whether the external program is operating properly.
    - Check whether the command line is correct.
      Contact a system administrator or a developer if the command line is no longer valid
      for the installed version of the external program.
Additional information:
    The full command line executed was:
    drbdadm -vvv --max-peers 7 -- --force create-md OpenNebula-Image-0-vm0-disk0/0

    The external command sent the following output data:
    drbdmeta 1001 v09 /dev/vg-drbdpool/OpenNebula-Image-0-vm0-disk0_00000 internal create-md 7 --force 

    The external command sent the follwing error information:
    open(/dev/vg-drbdpool/OpenNebula-Image-0-vm0-disk0_00000) failed: No such file or directory
    open(/dev/vg-drbdpool/OpenNebula-Image-0-vm0-disk0_00000) failed: No such file or directory
    Command 'drbdmeta 1001 v09 /dev/vg-drbdpool/OpenNebula-Image-0-vm0-disk0_00000 internal create-md 7 --force' terminated with exit code 20

Category:                           LinStorException
Class name:                         ExtCmdFailedException
Class canonical name:               com.linbit.extproc.ExtCmdFailedException
Generated at:                       Method 'execute', Source file 'DrbdAdm.java', Line #437

Error message:                      The external command 'drbdadm' exited with error code 20

Call backtrace:

    Method                                   Native Class:Line number
    execute                                  N      com.linbit.drbd.DrbdAdm:437
    simpleAdmCommand                         N      com.linbit.drbd.DrbdAdm:388
    createMd                                 N      com.linbit.drbd.DrbdAdm:217
    createVolumeMetaData                     N      com.linbit.linstor.core.DrbdDeviceHandler:1060
    createResourceMetaData                   N      com.linbit.linstor.core.DrbdDeviceHandler:1489
    createResource                           N      com.linbit.linstor.core.DrbdDeviceHandler:1138
    dispatchResource                         N      com.linbit.linstor.core.DrbdDeviceHandler:364
    run                                      N      com.linbit.linstor.core.DeviceManagerImpl$DeviceHandlerInvocation:1225
    run                                      N      com.linbit.WorkerPool$WorkerThread:179

END OF ERROR REPORT.

**Comment by deleteriousEffect** [comment]
Hi, this error looks like it's coming from Linstor itself, might be best to take it up with it's devs https://github.com/LINBIT/linstor-server.

Just a quick overview though, I'm seeing this: 

```
open(/dev/vg-drbdpool/OpenNebula-Image-0-vm0-disk0_00000) failed: No such file or directory
open(/dev/vg-drbdpool/OpenNebula-Image-0-vm0-disk0_00000) failed: No such file or directory
```


So it seems like the underlying storage didn't come back for some reason, might be best to start investigating there.

**Comment by ulide4** [comment]
Thanks, I opened an issue at the linstor repo with a little more info based on your followup.
https://github.com/LINBIT/linstor-server/issues/39

**Comment by ulide4** [comment]
Closing, see referenced issue for linstor server for resolution.
Thanks.
