### ISSUE TITLE
bug: VM boot failure for linstor-system

### ISSUE THREAD

**Issue by tetra12** [OpenNebula/addon-linstor#20]
Hello I'm trying to instantiate an `Alpine` image from the marketplace, but getting the error below. I've followed your `Linstor setup manual for OpenNebula` and was able to add Linstor Data and System stores.

```sh
Sun Dec  1 23:07:06 2024 [Z0][VMM][I]: Successfully execute virtualization driver operation: /bin/cat - >/var/lib/one//datastores/101/2/ds.xml.
Sun Dec  1 23:07:06 2024 [Z0][VMM][I]: Command execution fail (exit code: 255): cat << 'EOT' | /var/tmp/one/vmm/kvm/deploy '/var/lib/one//datastores/101/2/de>
Sun Dec  1 23:07:06 2024 [Z0][VMM][I]: XPath set is empty
Sun Dec  1 23:07:06 2024 [Z0][VMM][I]: error: Failed to create domain from /var/lib/one//datastores/101/2/deployment.0
Sun Dec  1 23:07:06 2024 [Z0][VMM][I]: error: Cannot check QEMU binary /usr/bin/qemu-kvm-one: No such file or directory
Sun Dec  1 23:07:06 2024 [Z0][VMM][I]: Could not create domain from /var/lib/one//datastores/101/2/deployment.0
Sun Dec  1 23:07:06 2024 [Z0][VMM][I]: ExitCode: 255
Sun Dec  1 23:07:06 2024 [Z0][VMM][I]: Successfully execute network driver operation: clean.
Sun Dec  1 23:07:06 2024 [Z0][VMM][I]: Failed to execute virtualization driver operation: deploy.
Sun Dec  1 23:07:06 2024 [Z0][VMM][E]: DEPLOY: XPath set is empty error: Failed to create domain from /var/lib/one//datastores/101/2/deployment.0 error: Cann>
Sun Dec  1 23:07:06 2024 [Z0][VM][I]: New LCM state is BOOT_FAILURE
```

Environment:

OS: Ubuntu 24.04.1
Nebula: 6.10
Linstor-client: 1.23.2
DRBD: 9.2.11

Storage:

![Screenshot from 2024-12-02 00-02-36](https://github.com/user-attachments/assets/994814f9-b4bd-4fae-b008-c5bbed4389da)

I created my Linstor resources with the following:
```sh
> cat ds.conf

NAME = linstor-data
DS_MAD = linstor
TM_MAD = linstor
TYPE = IMAGE_DS
DISK_TYPE = BLOCK
LINSTOR_RESOURCE_GROUP = "hdd-group"
COMPATIBLE_SYS_DS = 0
#AUTO_PLACE="1"
BRIDGE_LIST = "hyp0" #node names

> cat system.conf

NAME = linstor-system
TM_MAD = linstor
TYPE = SYSTEM_DS
DISK_TYPE = BLOCK
LINSTOR_RESOURCE_GROUP = "ssd-group"
#CLONE_MODE="snapshot"
#AUTO_PLACE="1"
BRIDGE_LIST = "hyp0" # node names
```

Pls help to debug this error :pray: . Thank you in advance !

**Comment by rp-** [comment]
This is not storage related, it seems you miss some qemu binaries/packages there:
```
Sun Dec  1 23:07:06 2024 [Z0][VMM][I]: error: Failed to create domain from /var/lib/one//datastores/101/2/deployment.0
Sun Dec  1 23:07:06 2024 [Z0][VMM][I]: error: Cannot check QEMU binary /usr/bin/qemu-kvm-one: No such file or directory
```

**Comment by drev74** [comment]
@rp- Have you even tried to understand the issue :thinking: 

Your plugin doesn't work with a fresh installation of the latest Nebula 6.10. I have set all up as per Nebula docs and all works fine, but your plugin.

Which package provides this `qemu-kvm-one`? Why are you referring to it from the `linstor` plugin?

Below is what I have installed for QEMU:

![Screenshot from 2024-12-02 16-28-05](https://github.com/user-attachments/assets/1e79cae4-4763-4531-babd-ffe7d0c598f7)

**Comment by rp-** [comment]
As it is a `-one` binary it must come from some opennebula package.

But this error has nothing to do with the linstor-addon, in the error above I see no traces of the linstor plugin or any code of it.

see. e.g. here:
https://forum.opennebula.io/t/could-not-create-domain-error/9727/3

it looks like this binary should be in: `opennebula-node-kvm`
