### ISSUE TITLE
Disk snapshot delete/revert not working

### ISSUE THREAD

**Issue by ulide4** [OpenNebula/addon-linstor#3]
Hi
Snapshot creation is working fine. Disk save is also working fine.
But deleting and reverting the snapshots does not work.
oned.log only gives following error message:

"Sat Dec  1 15:17:40 2018 [Z0][TM][D]: Message received: LOG I 1 Command execution failed (exit code: 1): /var/lib/one/remotes/tm/linstor/snap_delete srv486:/var/lib/one//datastores/0/1/disk.0 0 1 100

Sat Dec  1 15:17:40 2018 [Z0][TM][D]: Message received: TRANSFER FAILURE 1 -

Best Regards 
Uli

**Comment by deleteriousEffect** [comment]
tm/snapshot_delete isn't implemented, so you're going to get an error there.

What are you doing that makes OpenNebula call that action? In my testing, it used the datastore snapshot delete in all cases, so this would be really valuable to me. 

In the future, you should know that the most of the logs are going to be in syslog and those are usually helpful.

**Comment by ulide4** [comment]
Sunstone -> VMs -> Select a VM -> Storage
Here the camera symbol takes a snapshot. Then I can show the snapshots (left arrow) and select a snapshot. From here I tried revert or delete. That triggers the failed action. BTW, "save as" from here works just fine and creates a new image.

![image](https://user-images.githubusercontent.com/38238648/49337525-735c2e80-f614-11e8-9a5b-0fee6714edc2.png)

**Comment by ulide4** [comment]
fixed in v0.9.2
