### ISSUE TITLE
Installation instructions not working/ outdated

### ISSUE THREAD

**Issue by gucki** [OpenNebula/addon-linstor#6]
I setup a new debian buster test system and install opennebula and linstor there. Both for. Now I try to integrate them. 

In the first run the setup complained about a missing setuptool module. Running "apt-get install python-setuptools" solved it. But now fails with:

root@n1:/tmp/addon-linstor# python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to linstor_opennebula.egg-info/requires.txt
writing linstor_opennebula.egg-info/PKG-INFO
writing top-level names to linstor_opennebula.egg-info/top_level.txt
writing dependency_links to linstor_opennebula.egg-info/dependency_links.txt
reading manifest file 'linstor_opennebula.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'linstor_opennebula.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/one
copying build/lib.linux-x86_64-2.7/one/vm.py -> build/bdist.linux-x86_64/egg/one
copying build/lib.linux-x86_64-2.7/one/image.py -> build/bdist.linux-x86_64/egg/one
copying build/lib.linux-x86_64-2.7/one/driver_action.py -> build/bdist.linux-x86_64/egg/one
copying build/lib.linux-x86_64-2.7/one/extender.py -> build/bdist.linux-x86_64/egg/one
copying build/lib.linux-x86_64-2.7/one/__init__.py -> build/bdist.linux-x86_64/egg/one
copying build/lib.linux-x86_64-2.7/one/util.py -> build/bdist.linux-x86_64/egg/one
copying build/lib.linux-x86_64-2.7/one/consts.py -> build/bdist.linux-x86_64/egg/one
copying build/lib.linux-x86_64-2.7/one/datastore.py -> build/bdist.linux-x86_64/egg/one
byte-compiling build/bdist.linux-x86_64/egg/one/vm.py to vm.pyc
byte-compiling build/bdist.linux-x86_64/egg/one/image.py to image.pyc
byte-compiling build/bdist.linux-x86_64/egg/one/driver_action.py to driver_action.pyc
byte-compiling build/bdist.linux-x86_64/egg/one/extender.py to extender.pyc
byte-compiling build/bdist.linux-x86_64/egg/one/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/one/util.py to util.pyc
byte-compiling build/bdist.linux-x86_64/egg/one/consts.py to consts.pyc
byte-compiling build/bdist.linux-x86_64/egg/one/datastore.py to datastore.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying linstor_opennebula.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying linstor_opennebula.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying linstor_opennebula.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying linstor_opennebula.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying linstor_opennebula.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/linstor_opennebula-1.0.9-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing linstor_opennebula-1.0.9-py2.7.egg
Removing /usr/local/lib/python2.7/dist-packages/linstor_opennebula-1.0.9-py2.7.egg
Copying linstor_opennebula-1.0.9-py2.7.egg to /usr/local/lib/python2.7/dist-packages
linstor-opennebula 1.0.9 is already the active version in easy-install.pth
Installed /usr/local/lib/python2.7/dist-packages/linstor_opennebula-1.0.9-py2.7.egg
Processing dependencies for linstor-opennebula==1.0.9
Searching for python-linstor>=1.0.13
Reading https://pypi.org/simple/python-linstor/
Couldn't find index page for 'python-linstor' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for python-linstor>=1.0.13
error: Could not find suitable distribution for Requirement.parse('python-linstor>=1.0.13')

I already installed the python-linstor package:

root@n1:/tmp/addon-linstor# apt-get install python-linstor linstor-client
Reading package lists... Done
Building dependency tree       
Reading state information... Done
linstor-client is already the newest version (1.1.2-1).
python-linstor is already the newest version (1.1.2-1).
python-linstor set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

It'd be great if the install instructions could be updated/ completed. Thank you.

**Comment by rp-** [comment]
you are mixing python2 with python3.

python-linstor on deb/ubuntu is python3 only

**Comment by gucki** [comment]
Thanks @rp- , you are right. With "python3 setup.py install" it works.
