### ISSUE TITLE
Different linstor controller address than localhost

### ISSUE THREAD

**Issue by zheliazkov** [OpenNebula/addon-linstor#8]
Is there an options to change the linstor controller address or better - add multiple addresses the way the linstor-client works? 

By default analyzed from the logs its searching for linstor://localhost but there can be different controllers in a HA way that are on different machines.

BR, 
Plamen

**Comment by rp-** [comment]
https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#_plugin_attributes
