### ISSUE TITLE
Instantiation of multiple VMs

### ISSUE THREAD

**Issue by zheliazkov** [OpenNebula/addon-linstor#9]
If I try to instantiate more than 1 VM at a time on a linstor storage, the linstor is stopping to work due to multiple pvdisplay processes on the nodes hanging.

Does this happens to somebody else and is there a workaround?

**Comment by rp-** [comment]
I just tried to instantiate 5 VM's at a time and that worked, I admit it was just small alpine VM's, but netherless it worked.

If you have a recent linstor version lv-filters should be correctly set by the commands themself, but maybe it helps if you set a global lvm filter to ignore drbd devices while scanning.

**Comment by zheliazkov** [comment]
After the OS change (From Ubuntu) the problem doesn't exists, so I cannot give feedback for the solution. 

Thanks for the info/help!
